language: C++
dist: xenial
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8
      - cmake-data
      - cmake
    env:
      - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

before_install:
  - eval "${MATRIX_EVAL}"
install:
  - pip install --user py jinja2
  - python -c "import site;print(\"site.USER_BASE: {}\".format(site.USER_BASE))"
  - python -c "import py"
  - python -c "import jinja2"
script: cmake . && make && make test
